language: ruby

sudo: false

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.2
  - ruby-head
  - jruby
  - rbx-2

gemfile:
  - Gemfile
  - Gemfile.3-2
  - Gemfile.4-0
  - Gemfile.4-1
  - Gemfile.4-2

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile
    - rvm: jruby
      gemfile: Gemfile
    - rvm: rbx-2
      gemfile: Gemfile

notifications:
  email: false
  campfire:
    on_success: change
    rooms:
      - secure: "TP0fJ4aqXCRD7CaAgaYW7Pa22j4/uLChdBb59ob/sJvHtfi4Zx3I54xWApmp\nZl1KItFGCV8oQZhQl5hAmHJfJ+1gCNeBvIKwY6TsIyTmyDg1KcJUcJDrwYxO\ntAeYI2PvU5PtKMmpnfnwFQMxL+2nfWJWNzboBCDr4YvoFI+rN+A="

